# BPClassifier Pipeline: Steps 1-7

This notebook is the thin, readable front end. Core logic lives in `src/project_notebook.py`; model hyperparameters live in `src/model_config.py`.

## 0. Setup

In [1]:
import sys
from pathlib import Path

for candidate in (Path.cwd().resolve(), *Path.cwd().resolve().parents):
    if (candidate / "src" / "paths.py").is_file():
        if str(candidate) not in sys.path:
            sys.path.insert(0, str(candidate))
        PROJECT_ROOT = candidate
        break
else:
    raise RuntimeError("Could not find the HW2 project root from this notebook.")

PROJECT_ROOT

PosixPath('/home/tian/code/baruch/NLP_HW/HW2')

## 1. Configuration

In [2]:
from src.model_config import ZooRunConfig
from src.project_notebook import print_environment_report

zoo_cfg = ZooRunConfig.for_8gb_gpu(seed=42, show_progress=True)
print_environment_report(zoo_cfg)

Environment:
{
  "project_root": "/home/tian/code/baruch/NLP_HW/HW2",
  "python": "3.10.20",
  "platform": "Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39",
  "cache_dir": "/home/tian/code/baruch/NLP_HW/HW2/cache",
  "gold_labeled_exists": true,
  "target_profile": "8 GB CUDA GPU defaults, CPU fallback if CUDA is unavailable",
  "torch": {
    "torch": "2.11.0+cu126",
    "cuda_available": true,
    "cuda_device": "NVIDIA GeForce RTX 4060 Laptop GPU",
    "cuda_memory_gb": 8.0
  },
  "model_config": {
    "sentence_transformers_model_id": "sentence-transformers/all-MiniLM-L6-v2",
    "embedding_batch_size": 256,
    "finbert_batch_size": 16,
    "finbert_eval_batch_size": 32,
    "setfit_batch_size": 128,
    "setfit_num_epochs": [
      1,
      2
    ],
    "setfit_num_iterations": 10,
    "skip_finbert": false,
    "skip_setfit": false
  }
}

## 2. Sentence Pool and Gold Labels

This uses cached artifacts when available. To force Haiku arbitration and rewrite `cache/gold_labeled.parquet`, pass `extra_argv=["--use-api-check"]` and set `ANTHROPIC_API_KEY`.

In [3]:
from src.project_notebook import run_gold_standard_pipeline_report

run_gold_standard_pipeline_report(seed=zoo_cfg.seed)

Gold pipeline: completed.
max_transcripts None max_pool_rows None gold_n_target 3000
loaded pool rows from cache 55485 -> /home/tian/code/baruch/NLP_HW/HW2/cache/sentence_pool.parquet
pool rows 55485
loaded gold sample from cache 3000 -> /home/tian/code/baruch/NLP_HW/HW2/cache/gold_sample.parquet
judge cache llama3.1:8b -> /home/tian/code/baruch/NLP_HW/HW2/cache/labels_llama3.1_8b.parquet
judge cache qwen3:8b-q4_K_M -> /home/tian/code/baruch/NLP_HW/HW2/cache/labels_qwen3_8b-q4_K_M.parquet
judge cache gemma2:9b -> /home/tian/code/baruch/NLP_HW/HW2/cache/labels_gemma2_9b.parquet
sample rows 3000
haiku_api_usage_preview
merge skipped (pass --use-api-check to call Anthropic and write gold_labeled.parquet)
gold_labeled exists rows 3000 cols ['api_error', 'api_used', 'discord', 'gold_final', 'j1_label', 'j1_parse_fallback', 'j1_raw', 'j2_label', 'j2_parse_fallback', 'j2_raw', 'j3_label', 'j3_parse_fallback', 'j3_raw', 'sentence_id', 'source_file', 'text', 'tie_break_label']
frac_needs_haiku_api: 0.363
OK: gold_labeled.parquet rows=3000

## 3. Split and Handcrafted Features

In [4]:
from src.project_notebook import run_stratified_split_and_handcrafted_features_report

split_result = run_stratified_split_and_handcrafted_features_report(seed=zoo_cfg.seed)

Split and handcrafted features: completed.
Split core metadata:
{
  "rows_input": 3000,
  "rows_supervision": 3000,
  "seed": 42,
  "sentences_per_split": {
    "test": 543,
    "train": 1826,
    "val": 631
  },
  "transcripts_per_split": {
    "test": 26,
    "train": 79,
    "val": 26
  },
  "transcripts_total": 131
}
            sentence_id     source_file  gold_final split
AMD_Q1-2024.txt#0000154 AMD_Q1-2024.txt substantive train
AMD_Q1-2024.txt#0000052 AMD_Q1-2024.txt substantive train
AMD_Q1-2024.txt#0000346 AMD_Q1-2024.txt substantive train
AMD_Q1-2024.txt#0000038 AMD_Q1-2024.txt substantive train
AMD_Q1-2024.txt#0000174 AMD_Q1-2024.txt boilerplate train
 h01  h02  h03  h04  h05  h06  h07  h08
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
feature_columns: 30

## 4. Classifier Zoo, Ensembles, and Winner

The default config runs the full family set. For a quick local smoke check, use `ZooRunConfig.quick_non_transformer(seed=42)` instead.

In [5]:
from src.project_notebook import run_classifier_zoo_report

zoo_result = run_classifier_zoo_report(cfg=zoo_cfg)

Classifier zoo config:
Key hyperparameters:
{
  "recall_floor": 0.96,
  "embedding_batch_size": 256,
  "finbert_batch_size": 16,
  "finbert_eval_batch_size": 32,
  "setfit_batch_size": 128,
  "setfit_num_epochs": [
    1,
    2
  ],
  "setfit_num_iterations": 10,
  "skip_finbert": false,
  "skip_setfit": false
}
[zoo] start (OOF + test)

/home/tian/opt/miniconda/envs/nlp/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[zoo] sentence embeddings: all supervised rows …
[zoo] B/C/D OOF models …

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
E FinBERT OOF:   0%|                                                                                                                                                                                                                     | 0/5 [00:00<?, ?fold/s]
tokenize: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1976/1976 [00:00<00:00, 55433.68 examples/s]

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 31678.32it/s]
BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |
-----------------------------+------------+---------------------------------------------------------------------------------------
bert.embeddings.position_ids | UNEXPECTED |
classifier.bias              | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3]) vs model:torch.Size([2])
classifier.weight            | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3, 768]) vs model:torch.Size([2, 768])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

  FinBERT val:   0%|                                                                                                                                                                                                                   | 0/16 [00:00<?, ?batch/s]
  FinBERT val:  31%|███████████████████████████████████████████████████████████████▍                                                                                                                                           | 5/16 [00:00<00:00, 41.68batch/s]
  FinBERT val:  62%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                           | 10/16 [00:00<00:00, 39.61batch/s]
  FinBERT val:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 15/16 [00:00<00:00, 41.77batch/s]
E FinBERT OOF:  20%|█████████████████████████████████████████                                                                                                                                                                    | 1/5 [00:15<01:03, 15.93s/fold]
tokenize: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1974/1974 [00:00<00:00, 55236.81 examples/s]

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 33165.03it/s]
BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |
-----------------------------+------------+---------------------------------------------------------------------------------------
bert.embeddings.position_ids | UNEXPECTED |
classifier.bias              | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3]) vs model:torch.Size([2])
classifier.weight            | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3, 768]) vs model:torch.Size([2, 768])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

  FinBERT val:   0%|                                                                                                                                                                                                                   | 0/16 [00:00<?, ?batch/s]
  FinBERT val:  31%|███████████████████████████████████████████████████████████████▍                                                                                                                                           | 5/16 [00:00<00:00, 42.46batch/s]
  FinBERT val:  62%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                           | 10/16 [00:00<00:00, 44.10batch/s]
  FinBERT val:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 15/16 [00:00<00:00, 40.18batch/s]
E FinBERT OOF:  40%|██████████████████████████████████████████████████████████████████████████████████                                                                                                                           | 2/5 [00:33<00:50, 16.72s/fold]
tokenize: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1938/1938 [00:00<00:00, 66302.02 examples/s]

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15201.14it/s]
BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |
-----------------------------+------------+---------------------------------------------------------------------------------------
bert.embeddings.position_ids | UNEXPECTED |
classifier.bias              | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3]) vs model:torch.Size([2])
classifier.weight            | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3, 768]) vs model:torch.Size([2, 768])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

  FinBERT val:   0%|                                                                                                                                                                                                                   | 0/17 [00:00<?, ?batch/s]
  FinBERT val:  24%|███████████████████████████████████████████████▊                                                                                                                                                           | 4/17 [00:00<00:00, 38.23batch/s]
  FinBERT val:  53%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                               | 9/17 [00:00<00:00, 41.08batch/s]
  FinBERT val:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 14/17 [00:00<00:00, 38.28batch/s]
E FinBERT OOF:  60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                  | 3/5 [00:47<00:31, 15.82s/fold]
tokenize: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1972/1972 [00:00<00:00, 65258.33 examples/s]

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 30833.70it/s]
BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |
-----------------------------+------------+---------------------------------------------------------------------------------------
bert.embeddings.position_ids | UNEXPECTED |
classifier.bias              | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3]) vs model:torch.Size([2])
classifier.weight            | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3, 768]) vs model:torch.Size([2, 768])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

  FinBERT val:   0%|                                                                                                                                                                                                                   | 0/16 [00:00<?, ?batch/s]
  FinBERT val:  31%|███████████████████████████████████████████████████████████████▍                                                                                                                                           | 5/16 [00:00<00:00, 40.89batch/s]
  FinBERT val:  62%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                           | 10/16 [00:00<00:00, 42.03batch/s]
  FinBERT val:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 15/16 [00:00<00:00, 42.35batch/s]
E FinBERT OOF:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 4/5 [01:05<00:16, 16.38s/fold]
tokenize: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1968/1968 [00:00<00:00, 64043.62 examples/s]

Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 24548.09it/s]
BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |
-----------------------------+------------+---------------------------------------------------------------------------------------
bert.embeddings.position_ids | UNEXPECTED |
classifier.bias              | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3]) vs model:torch.Size([2])
classifier.weight            | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3, 768]) vs model:torch.Size([2, 768])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

  FinBERT val:   0%|                                                                                                                                                                                                                   | 0/16 [00:00<?, ?batch/s]
  FinBERT val:  31%|███████████████████████████████████████████████████████████████▍                                                                                                                                           | 5/16 [00:00<00:00, 40.74batch/s]
  FinBERT val:  62%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                           | 10/16 [00:00<00:00, 40.44batch/s]
  FinBERT val:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 15/16 [00:00<00:00, 39.02batch/s]
tokenize (full TV): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2457/2457 [00:00<00:00, 57808.17 examples/s]
Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 15667.55it/s]
BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |
-----------------------------+------------+---------------------------------------------------------------------------------------
bert.embeddings.position_ids | UNEXPECTED |
classifier.bias              | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3]) vs model:torch.Size([2])
classifier.weight            | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3, 768]) vs model:torch.Size([2, 768])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Writing model shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.36it/s]
F SetFit OOF:   0%|                                                                                                                                                                                                                      | 0/5 [00:00<?, ?fold/s]
Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 3068.91it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1976/1976 [00:00<00:00, 69090.39 examples/s]
***** Running training *****
  Num unique pairs = 39520
  Batch size = 128
  Num epochs = 1

F SetFit OOF:  20%|█████████████████████████████████████████                                                                                                                                                                    | 1/5 [02:29<09:57, 149.43s/fold]
Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 3721.65it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1974/1974 [00:00<00:00, 63528.12 examples/s]
***** Running training *****
  Num unique pairs = 39480
  Batch size = 128
  Num epochs = 1

F SetFit OOF:  40%|██████████████████████████████████████████████████████████████████████████████████                                                                                                                           | 2/5 [04:23<06:25, 128.48s/fold]
Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 4548.18it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1938/1938 [00:00<00:00, 64468.39 examples/s]
***** Running training *****
  Num unique pairs = 38760
  Batch size = 128
  Num epochs = 1

F SetFit OOF:  60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                  | 3/5 [06:55<04:38, 139.44s/fold]
Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 4579.81it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1972/1972 [00:00<00:00, 68701.40 examples/s]
***** Running training *****
  Num unique pairs = 39440
  Batch size = 128
  Num epochs = 1

F SetFit OOF:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 4/5 [08:49<02:09, 129.36s/fold]
Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 4358.00it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1968/1968 [00:00<00:00, 57438.63 examples/s]
***** Running training *****
  Num unique pairs = 39360
  Batch size = 128
  Num epochs = 1

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 3780.97it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2457/2457 [00:00<00:00, 69324.77 examples/s]
***** Running training *****
  Num unique pairs = 49140
  Batch size = 128
  Num epochs = 1

Writing model shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.33it/s]
Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 1847.93it/s]
Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 3306.37it/s]

[zoo] done.
          family_id  test_macro_f1  test_accuracy  test_precision_boilerplate  test_recall_boilerplate  test_f1_boilerplate  test_precision_substantive  test_recall_substantive  test_f1_substantive  test_confusion_matrix  eligible_oof  threshold  threshold_std_across_folds  train_seconds  approx_infer_sents_per_sec notes
          E_finbert       0.866598       0.889503                    0.871622                 0.758824             0.811321                    0.896203                 0.949062             0.921875 [[129, 41], [19, 354]]          True      0.148                    0.071334      88.816718                5.512689e+02
           F_setfit       0.841078       0.867403                    0.822368                 0.735294             0.776398                    0.884910                 0.927614             0.905759 [[125, 45], [27, 346]]          True      0.028                    0.019467     886.900619                3.318591e+03
    G_ensemble_mean       0.815711       0.856354                    0.889831                 0.617647             0.729167                    0.847059                 0.965147             0.902256 [[105, 65], [13, 360]]          True      0.417                    0.020314       0.000000                3.109070e+04
  C_histgb_enriched       0.802203       0.843462                    0.840000                 0.617647             0.711864                    0.844498                 0.946381             0.892541 [[105, 65], [20, 353]]          True      0.337                    0.024782       6.663807                1.866307e+05
H_ensemble_rankmean       0.798584       0.841621                    0.844262                 0.605882             0.705479                    0.840855                 0.949062             0.891688 [[103, 67], [19, 354]]          True      0.288                    0.015564       0.000000                3.109070e+04
  B_logreg_enriched       0.750345       0.817680                    0.890110                 0.476471             0.620690                    0.803097                 0.973190             0.880000  [[81, 89], [10, 363]]          True      0.016                    0.020717       0.151334                6.725453e+04
         D_fasttext       0.746624       0.813996                    0.870968                 0.476471             0.615970                    0.802222                 0.967828             0.877278  [[81, 89], [12, 361]]          True      0.103                    0.059125       1.322090                8.430863e+04
            A_rules       0.506494       0.688766                    0.511628                 0.129412             0.206573                    0.704000                 0.943700             0.806415 [[22, 148], [21, 352]]          True      0.276                    0.002332       0.000000                1.320782e+07
Winner:
{
  "family_id": "G_ensemble_mean",
  "eligible_oof": true,
  "threshold": 0.417,
  "oof_macro_f1": 0.8084315774238091,
  "threshold_std_across_folds": 0.020313542280951394,
  "train_seconds": 0.0,
  "notes": "",
  "test_accuracy": 0.856353591160221,
  "test_macro_f1": 0.8157111528822054,
  "test_precision_boilerplate": 0.8898305084745762,
  "test_recall_boilerplate": 0.6176470588235294,
  "test_f1_boilerplate": 0.7291666666666666,
  "test_precision_substantive": 0.8470588235294118,
  "test_recall_substantive": 0.9651474530831099,
  "test_f1_substantive": 0.9022556390977443,
  "test_confusion_matrix": [
    [
      105,
      65
    ],
    [
      13,
      360
    ]
  ],
  "approx_infer_sents_per_sec": 31090.702009001565
}
Saved result artifacts:
{
  "leaderboard_csv": "/home/tian/code/baruch/NLP_HW/HW2/cache/zoo_leaderboard.csv",
  "leaderboard_json": "/home/tian/code/baruch/NLP_HW/HW2/cache/zoo_leaderboard.json",
  "winner_summary": "/home/tian/code/baruch/NLP_HW/HW2/cache/zoo_winner/winner_summary.json",
  "winner_manifest": "/home/tian/code/baruch/NLP_HW/HW2/cache/zoo_winner/winner_manifest.json"
}